### ISSUE TITLE
Is there anyway to clear the position information?

### ISSUE THREAD

**Issue by JunyuanZheng** [ethanselzer/react-cursor-position#2]
Hi,

This tool works perfectly for our project. However, I have a question, is that possible to reset the cursor information when it moves out the object?

Thanks!

**Comment by ethanselzer** [comment]
Hi, 

Thanks for opening your issue. The feature you describe is not currently supported, but I would like to support it. To achieve the greatest utility from the implementation I would like to make it as general as possible. I propose child components and subscribers to `onCursorPositionChanged` receive a new Boolean property that would be set to true when the cursor is outside the bounds of the target element. Do you think that would address the use case you are inquiring about?

I'm very happy that react-cursor-position is working well for you!

**Comment by JunyuanZheng** [comment]
That would be perfect! Thank you so much!

**Comment by JunyuanZheng** [comment]
I will also study the code. I might be able to implement this.

**Comment by ethanselzer** [comment]
Okay great! I will get started on adding this feature. I think it will be ready in one to two days.

**Comment by ethanselzer** [comment]
The feature is ready! Child components and subscribers to `onCursorPositionChanged` will receive a new property named `isOutside`.  Please see updated [code release](https://github.com/ethanselzer/react-cursor-position/releases/tag/v1.2.0) and [npm package @ V1.2](https://www.npmjs.com/package/react-cursor-position).

Thanks again for opening and issue. Please let me know if the new release addresses your use case.

**Comment by JunyuanZheng** [comment]
Thank you so much!

**Comment by JunyuanZheng** [comment]
Sorry to bother you again.

This code is working perfectly now. But I am just wondering Is there any way I can override the onMouseLeave function to make x, y equal to null?

Thanks!

**Comment by ethanselzer** [comment]
Please to don't apologize. My goal is to make react-cursor-position useful to you. We are on the same team!

It looks like you closed the issue. Does that mean you found a solution?

I'm envisioning an enhancement to the API that would allow consumers to map the name and values of child component props (see below). Would that be helpful to you?

```
mapProps: (props) => {
  if (props.cursorPosition.isOutside) {
    return {
      cursorPosition: {
        x: null,
        y: null,
     };
  }
  return props;
}
```

**Comment by JunyuanZheng** [comment]
Oh, thanks for the reply. I rethink about this question, and I think adding another function doesn't make any sense, so I close this issue.
