### ISSUE TITLE
Constants import path

### ISSUE THREAD

**Issue by tekbreak** [ethanselzer/react-cursor-position#21]
I think you miss "./" in the path to constants.js file
In the file ReactCursorPosition.js, line 6
`import * as constants from 'constants';`

The correct path is:
`import * as constants from './constants';`

I know you way is also accepted, but it can affect aliases created by webpack

**Comment by ethanselzer** [comment]
@tekbreak - Thanks for reporting this issue! I really appreciate it. I think it is corrected in [release v2.4.1](https://github.com/ethanselzer/react-cursor-position/releases/tag/v2.4.1). Please have a look! If you find react-cursor-position useful, please consider starring it on GitHub. Starring helps to grow the project and that benefits everyone who uses it. Thanks again!

**Comment by ethanselzer** [comment]
Closing as fixed in [v2.4.1](https://github.com/ethanselzer/react-cursor-position/releases/tag/v2.4.1)
