### ISSUE TITLE
Incorrect position after mouse-wheel scroll

### ISSUE THREAD

**Issue by aronhelser** [ethanselzer/react-cursor-position#22]
I'm seeing some incorrect y-positions after I scroll using my mouse wheel - the cursor remains inside the component. If I scroll by dragging the scroll bar, it's correct.

ReactCursorPosition and the component it's wrapping are inside a `div `with `overfow-y: auto`.

I'm happy to provide more detail if needed.

**Comment by ethanselzer** [comment]
@aronhelser - Thanks for opening this issue. I'm wondering if the incorrect y-position you are experiencing persists after moving the mouse or only before the mouse is moved. Please let me know.

**Comment by aronhelser** [comment]
It does persist after I move the mouse, but it's corrected if I exit the
element and then re-enter. I'm guessing that something that happens during
mouse-leave or mouse-enter needs to be triggered when the element is
scrolled.

What I'm not sure about is if you can get scroll events for your element
when it's just inside another element that's scrolled? (since that's what's
happening here).

**Comment by ethanselzer** [comment]
Hi @aronhelser - The [latest release of react-cursor-position](https://github.com/ethanselzer/react-cursor-position/releases/tag/v2.5.0) introduces the `reset` method, which may correct the problem you identified in this issue. Please see the [demo example](https://ethanselzer.github.io/react-cursor-position/#/reset) for details. Thanks again for opening this issue. I appreciate it.

**Comment by ethanselzer** [comment]
@aronhelser - I'm closing this issue for now. If you find your use case is not corrected by v2.5.0, please reopen the issue. Thanks!

**Comment by aronhelser** [comment]
Thanks! Sorry I haven't been able to confirm - I should be able to test
soon.
