### ISSUE TITLE
Wrong Coordinates when I have a single div centered using margin 0px auto 

### ISSUE THREAD

**Issue by singhshashi** [ethanselzer/react-cursor-position#4]
The library does not work as expected for a simple use case.  Please see the following:

![react-cursor-position-bug](https://cloud.githubusercontent.com/assets/371601/23294401/4350cfa0-fa91-11e6-891b-18caf257e6b5.gif)

I click to bring the focus on the browser screen and once that is there, you can see that the mouse is outside the div but it still shows as inside. The reason for this is that you are wrapping the child with a div and that is actually much wider because of the css I have used to center the child div which is grey. 

So even though the pointer is outside the child div, since it is inside the div you have used to wrap, the values in cursorPosition is incorrect. I am not very sure whether the approach of wrapping in a div will work.

**Comment by ethanselzer** [comment]
@singhshashi - Thanks for raising this issue! I hope I can help out. I think the most common pattern for using react-cursor-position is to constrain the width of the element it renders. You can achieve this by wrapping it in a container or applying dimensions directly to ReactCursorPosition, using either the `className` or `style` props. Here is a [live example](http://codepen.io/ethanselzer/pen/ryayLK) you can experiment with. In your design, is it possible for you to apply a width to your ReactCursorComponent instance? 

Remember react-cursor-position is designed to track the mouse cursor relative to the element it renders, not its child elements.

Please let me know how it goes!

**Comment by ethanselzer** [comment]
@singhshashi - I'm closing this for now. If you would like further help, please let me know. Best of luck!
