### ISSUE TITLE
Compatibility with React 15.5

### ISSUE THREAD

**Issue by damien916** [ethanselzer/react-cursor-position#5]
Hello @ethanselzer :)
I use react-image-magnify with react 15.5 and i have this error:

> ReactCursorPosition: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Have you planned to update react-cursor-position to make it compatible with react 15.5 ?

**Comment by ethanselzer** [comment]
Hi @damien916!

Thanks for asking. Yes, react-cursor-position should be compatible with React 15.5 as of the [2.0 release](https://github.com/ethanselzer/react-cursor-position/releases/tag/v2.0.0). I am in the process of upgrading other react-image-magnify dependencies on the path to full React 15.5 support. I just opened an [issue](https://github.com/ethanselzer/react-image-magnify/issues/10) to track progress. Thank you for raising my awareness on the importance of this upgrade!

**Comment by damien916** [comment]
Hi @ethanselzer, it's a great news, thank you again for your job !

**Comment by ethanselzer** [comment]
Closing in favor of tracking this issue on https://github.com/ethanselzer/react-image-magnify/issues/10.
